### ISSUE TITLE
Automatizar deploy

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/opendataday#8]
Pelo que entendi o deploy é feito pelo `lektor deploy`, que pusha para a branch `gh-pages`. Seria bom ter o deploy automático para todas as vezes que a branch principal for atualizada (podemos inclusive mudar isso da branch, para pegar a principal e a `main` sempre refletir o estado atual do site).

No Travis o passo de deploy estava assim:

```
deploy:
  provider: script
  script: lektor deploy ci
  skip_cleanup: true
  on:
    branch: master
```

Devemos adicionar esse passo como novo workflow no Github Actions. Ele deverá ser executado apenas quando a `main` for atualizada.
